### ISSUE TITLE
Record a specific window (macOS)

### ISSUE THREAD

**Issue by richiemcilroy** [CapSoftware/Cap#23]
**Requirements**
- When clicking "Window" display option, open a context menu with the names of available windows to capture from (e.g. whatever apps are open, Spotify, Chrome, VSCode, etc...).
- When an option is selected, focus on that window and bring it into view.
- When recording, only record the parameters of that Window (size, position, etc). 
-- For now, this can just be done by adding a filter to the Ffmpeg command, or directly editing the raw frame data in `media.rs`.
- Show the "Window" display option as the selected option

![Screenshot 2024-04-11 at 13 45 26](https://github.com/CapSoftware/Cap/assets/33632126/393ff462-a074-40ca-98ab-3411d5da5094)

You can use [this guide](https://github.com/CapSoftware/Cap/blob/main/CONTRIBUTING.md#how-do-i-run-the-desktop-app-locally-without-needing-to-use-auth) to help you get started developing locally as quickly as possible.

**Comment by devrajgadhvi** [comment]
I am trying to implement this, currently I am setting up dev environment and then procced with the issue further. Recently found out about Cap from a opensource thread. You can take this as /attempt #23

Out of the two options which one is preferred more? As I am going to learn about both anyway so I will focus on that one more.

**Comment by devrajgadhvi** [comment]
@richiemcilroy Is it possible to test this on windows by any chance? Dropped my macbook , it will take sometime to get it back :(

**Comment by syedbarimanjan** [comment]
> @richiemcilroy Is it possible to test this on windows by any chance? Dropped my macbook , it will take sometime to get it back :(

you will get some errors on windows if you are able to solve them then you are good to go.

**Comment by ItsEeleeya** [comment]
For macOS, if we add support for Safari in the web version then in theory we could share the logic with the desktop app?
(_I'm not totally sure if the WebKit that's used for the WebView supports this_)

I believe one of the benefits to that is how well integrated it is with macOS, which would make implementing and maintaining it much easier. It already lets you easily select a video and gives the same recording options in the menu bar as if you were using FaceTime or some other app like Discord.
Later on this would also work on Linux.

If this is ok instead of doing it with ffmpeg, I'll start working on it.

**Comment by ItsEeleeya** [comment]
Hey @daidi, I'm currently working on this and it should be ready for review during next week.

**Comment by richiemcilroy** [comment]
hey @daidi - we're close to releasing Cap v0.5, which includes support for this. Cheers!
