### ISSUE TITLE
Missed stop and cancel features

### ISSUE THREAD

**Issue by rodion-m** [CapSoftware/Cap#34]
Hello! At first, thanks a lot for a great tool!

I didn't get how stop the recording quiclkly? (the only way the I found is to open Cap window, or it's by design?)

Also, I missed a recording cancellation feature.

**Comment by richiemcilroy** [comment]
Thank you @rodion-m! 

With the desktop app, there's a "Stop" icon that appears when you stop recording. You can just click it and it'll open the window and stop the recording.

On the web app, you have to navigate back to the Cap tab and stop the recording. Will make it soon so that if you click the "stop screen sharing" button, it'll stop the recording gracefully from there.
